// <auto-generated />
using System;
using System.Collections.Generic;
using CalangoAPI.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CalangoAPI.API.Migrations
{
    [DbContext(typeof(OnibusDbContext))]
    [Migration("20260701173802_AdicionarMalhaViaria")]
    partial class AdicionarMalhaViaria
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CalangoAPI.Domain.Entities.Frota.Onibus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Quilometragem")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Onibus");
                });

            modelBuilder.Entity("CalangoAPI.Domain.Entities.Malha.Parada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DistanciaInicialKm")
                        .HasColumnType("numeric");

                    b.Property<string>("NomeLocalidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<Guid>("RotaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RotaId");

                    b.ToTable("Paradas");
                });

            modelBuilder.Entity("CalangoAPI.Domain.Entities.Malha.Rota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.PrimitiveCollection<List<int>>("PontosDeVendaIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.ToTable("Rotas");
                });

            modelBuilder.Entity("CalangoAPI.Domain.Entities.Malha.Parada", b =>
                {
                    b.HasOne("CalangoAPI.Domain.Entities.Malha.Rota", null)
                        .WithMany("Paradas")
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CalangoAPI.Domain.Entities.Malha.Rota", b =>
                {
                    b.Navigation("Paradas");
                });
#pragma warning restore 612, 618
        }
    }
}
