// <auto-generated />
using System;
using System.Collections.Generic;
using CalangoAPI.Infrastructure.Data.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace CalangoAPI.API.Migrations
{
    [DbContext(typeof(OnibusDbContext))]
    partial class OnibusDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "10.0.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("CalangoAPI.Domain.Entities.Frota.Onibus", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Capacidade")
                        .HasColumnType("integer");

                    b.Property<string>("Placa")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("character varying(10)");

                    b.Property<int>("Quilometragem")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<string>("Tipo")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.ToTable("Onibus");
                });

            modelBuilder.Entity("CalangoAPI.Domain.Entities.Malha.Parada", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<decimal>("DistanciaInicialKm")
                        .HasColumnType("numeric");

                    b.Property<string>("NomeLocalidade")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<int>("Ordem")
                        .HasColumnType("integer");

                    b.Property<Guid>("RotaId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RotaId");

                    b.ToTable("Paradas");
                });

            modelBuilder.Entity("CalangoAPI.Domain.Entities.Malha.Rota", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.PrimitiveCollection<List<int>>("PontosDeVendaIds")
                        .IsRequired()
                        .HasColumnType("integer[]");

                    b.HasKey("Id");

                    b.ToTable("Rotas");
                });

            modelBuilder.Entity("CalangoAPI.Domain.Entities.Operacional.Viagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataPartida")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid?>("MotoristaId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("OnibusId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RotaId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.HasKey("Id");

                    b.HasIndex("MotoristaId");

                    b.HasIndex("OnibusId");

                    b.HasIndex("RotaId");

                    b.ToTable("Viagens");
                });

            modelBuilder.Entity("CalangoAPI.Domain.Entities.RecursosHumanos.Motorista", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("CartaConducao")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Nome")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.ToTable("Motoristas");
                });

            modelBuilder.Entity("CalangoAPI.Domain.Entities.Vendas.Passagem", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("Assento")
                        .HasColumnType("integer");

                    b.Property<DateTime>("DataCompra")
                        .HasColumnType("timestamp with time zone");

                    b.Property<Guid>("ParadaDestinoId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("ParadaOrigemId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("PassageiroId")
                        .HasColumnType("uuid");

                    b.Property<decimal>("ValorPago")
                        .HasColumnType("numeric");

                    b.Property<Guid>("ViagemId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ViagemId", "Assento")
                        .IsUnique();

                    b.ToTable("Passagens");
                });

            modelBuilder.Entity("CalangoAPI.Domain.Entities.Malha.Parada", b =>
                {
                    b.HasOne("CalangoAPI.Domain.Entities.Malha.Rota", null)
                        .WithMany("Paradas")
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("CalangoAPI.Domain.Entities.Operacional.Viagem", b =>
                {
                    b.HasOne("CalangoAPI.Domain.Entities.RecursosHumanos.Motorista", null)
                        .WithMany()
                        .HasForeignKey("MotoristaId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("CalangoAPI.Domain.Entities.Frota.Onibus", null)
                        .WithMany()
                        .HasForeignKey("OnibusId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("CalangoAPI.Domain.Entities.Malha.Rota", null)
                        .WithMany()
                        .HasForeignKey("RotaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("CalangoAPI.Domain.Entities.Malha.Rota", b =>
                {
                    b.Navigation("Paradas");
                });
#pragma warning restore 612, 618
        }
    }
}
